language: node_js

before_script:
  - npm install
  - npm run build

deploy:
  - provider: npm
    skip_cleanup: true
    api_key: $NPM_API_KEY
    email: "arielhernandezmusa@gmail.com"
    on:
      tags: true
